### ISSUE TITLE
How to update templates in existing forks

### ISSUE THREAD

**Issue by anders-kolstad** [NINAnor/ecRxiv#13]
Not sure how to do this. If I change something in any of the templates under `indicators/`, I can of coarse sync the fork, but since I already probaly will have renames the folders in my forked repo, the newly updated template will emerge inside a new folder, and it will not attampt to merge with my existing template(workgin document.

**Comment by frafra** [comment]
git is usually smart enough to understand that a file has been renamed, even when it has been edited. I would suggest using [git mv](https://git-scm.com/docs/git-mv) for all the other cases.
I hope I have understood your problem correctly 😄

You can also consider using tools that generate a project from a template, such as [copier](https://copier.readthedocs.io/en/stable/). We use it for various [Python projects in NINA](https://github.com/NINAnor/python-template).
