### ISSUE TITLE
Read the xlsx metadata in trhe qmd

### ISSUE THREAD

**Issue by anders-kolstad** [NINAnor/ecRxiv#14]
Why are we manually entering the metadata in the qmd when we have alrady typed it into the xlsx?

- [x] Update qmd template

**Comment by DrMattG** [comment]
Something like this? https://github.com/NINAnor/ecRxiv/blob/2d391fb3864536becbb23a2135e3b71b6b7c6a89/template.qmd#L59

**Comment by anders-kolstad** [comment]
I thnk I alreay fixed this, but forgot to tick the box. The metadata is always names the same, and in the same place insice the indicator folde, so we dont need to write the parh:

https://github.com/NINAnor/ecRxiv/blob/26baf4bd91cd28e6bc97588f096f09f9f49cbd67/indicators/rename-folder-after-your-indicator/R/document_indicator_here_and%20rename_file.qmd#L39
